version: "3.3"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es
    environment:
      - node.name=es
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    networks:
      - integration_test
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD",
          "curl", 
          "--fail" ,
          "http://localhost:9200/_cluster/health?wait_for_status=green&timeout=1s",
          "||",
          "exit",
          "1"
        ]
      interval: 10s
      timeout: 10s
      retries: 120
volumes:
  esdata01:
    driver: local

networks:
  integration_test:
    driver: bridge
